version: "2.2"
services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "reallyStrongPwd123"
      ACCEPT_EULA: "Y"
